<?xml version="1.0" encoding="utf-8"?><Database Name="DBGR76" Class="AccauntDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IMANOV\MYSQL;Initial Catalog=DBGR76;Integrated Security=True" SettingsObjectName="WindowsFormsApp46.Properties.Settings" SettingsPropertyName="DBGR76ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.USERS" Member="USERs">
    <Type Name="USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SURNAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>